# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestAppStore' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'ObjectMapper', '~> 2.2'
  pod 'AlamofireObjectMapper', '~> 4.1'
  pod 'SDWebImage', '~> 4.0'
  pod 'ImageSlideshow', '~> 1.2'
  pod 'ImageSlideshow/Alamofire'
  pod 'Cosmos', '~> 9.0'

  # Pods for TestAppStore

end
